<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Welcome Back Admin Comphy_w-50</name>
   <tag></tag>
   <elementGuidId>3967e679-2305-4311-8fc7-50222c3c119e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.w-50</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cms-comphy.herokuapp.com/public/img/Orange (1).png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-50</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-gradient-warning&quot;]/div[@class=&quot;full-width flex-center&quot;]/div[@class=&quot;row full-width flex-center&quot;]/div[@class=&quot;col-xl-5 col-lg-12 col-md-9&quot;]/div[@class=&quot;card o-hidden border-0 shadow-lg my-5&quot;]/div[@class=&quot;card-body p-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;p-5&quot;]/div[@class=&quot;text-center&quot;]/img[@class=&quot;w-50&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cms-comphy.herokuapp.com/public/img/Orange (1).png']</value>
   </webElementXpaths>
</WebElementEntity>
